// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbOT5fLimABiq0Xz7LP1Bk-Q8UDQE3Ve0',
    appId: '1:1041768699980:web:bd384fe0d3429e12e3bce9',
    messagingSenderId: '1041768699980',
    projectId: 'dayflow-10f7b',
    authDomain: 'dayflow-10f7b.firebaseapp.com',
    storageBucket: 'dayflow-10f7b.firebasestorage.app',
    measurementId: 'G-0M1JBQ23FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6-wrMzH7YUIgSci8eAKBnbNIaC2x67js',
    appId: '1:1041768699980:android:e002e34d7587b510e3bce9',
    messagingSenderId: '1041768699980',
    projectId: 'dayflow-10f7b',
    storageBucket: 'dayflow-10f7b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbOT5fLimABiq0Xz7LP1Bk-Q8UDQE3Ve0',
    appId: '1:1041768699980:web:bd384fe0d3429e12e3bce9',
    messagingSenderId: '1041768699980',
    projectId: 'dayflow-10f7b',
    authDomain: 'dayflow-10f7b.firebaseapp.com',
    storageBucket: 'dayflow-10f7b.firebasestorage.app',
    measurementId: 'G-0M1JBQ23FT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDygIXys3EmD3m32ZSUr4zDEvxYpjKaFWM',
    appId: '1:1041768699980:ios:deb72b9dbb917865e3bce9',
    messagingSenderId: '1041768699980',
    projectId: 'dayflow-10f7b',
    storageBucket: 'dayflow-10f7b.firebasestorage.app',
    iosBundleId: 'com.example.dayflow',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDygIXys3EmD3m32ZSUr4zDEvxYpjKaFWM',
    appId: '1:1041768699980:ios:deb72b9dbb917865e3bce9',
    messagingSenderId: '1041768699980',
    projectId: 'dayflow-10f7b',
    storageBucket: 'dayflow-10f7b.firebasestorage.app',
    iosBundleId: 'com.example.dayflow',
  );

}