// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw4lDaC7Ffg7H1RQ7Vq4dsN7tCQ0VdBLQ',
    appId: '1:618409045853:web:39535debe3d0a6675902b4',
    messagingSenderId: '618409045853',
    projectId: 'dayflowbabo',
    authDomain: 'dayflowbabo.firebaseapp.com',
    storageBucket: 'dayflowbabo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeDx7Upk85BCcKNrlG2zBRzU49-8V9wMM',
    appId: '1:618409045853:android:f33de66b95e09c125902b4',
    messagingSenderId: '618409045853',
    projectId: 'dayflowbabo',
    storageBucket: 'dayflowbabo.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw4lDaC7Ffg7H1RQ7Vq4dsN7tCQ0VdBLQ',
    appId: '1:618409045853:web:0cfe1e627ba3287a5902b4',
    messagingSenderId: '618409045853',
    projectId: 'dayflowbabo',
    authDomain: 'dayflowbabo.firebaseapp.com',
    storageBucket: 'dayflowbabo.firebasestorage.app',
  );
}
